"""empty message

Revision ID: 62fa197f8f61
Revises: 3996afb31fb3
Create Date: 2019-06-29 22:38:50.257742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fa197f8f61'
down_revision = '3996afb31fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'order_id')
    # ### end Alembic commands ###
